#!/usr/bin/env bash

# Undo node
n-uninstall -y

# Restore bashrc
mv ~/.bashrc_bak ~/.bashrc
source ~/.bashrc

# Undo Core Install
sudo apt -y purge curl htop stow tmux build-essential wireshark golang fzf lsof kdenlive i3 gimp ccache ninja-build yarn python3-pip xclip slack dconf-editor nvidia-settings brave-browser pavucontrol clangd screenkey lua tldr

# Remove orphaned packages
sudo apt -y autoremove
