- hosts: localhost
  vars_prompt:
    - name: password
      prompt: Enter password
      private: yes

  tasks:
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/zsh-setup.yml
