- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/hosts.yml
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    # After node-setup, I have to restart terminal to access n command
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    # After zsh-setup, I have to log out and in to use zsh
    - include: tasks/zsh-setup.yml
      # May need to run :PlugInstall and some plugin specific commands
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
      # May have to clear and regenerate font cache via:
      # fc-cache -f -v
      # Or restart terminal
    - include: tasks/fonts.yml
    - include: tasks/productivity.yml
