- name: Install System Packages
  become: true
  apt:
    name: [ "curl", "vim" ]
  tags:
    - install
    - core
- name: Back up .bashrc so we can revert if needed
  shell: cp ~/.bashrc ~/.bashrc_bak
  tags:
    - install
    - core






